{
  "comments": [
    {
      "key": {
        "uuid": "5ac10518_cf5afd4f",
        "filename": "functest/utils/functest_logger.py",
        "patchSetId": 13
      },
      "lineNbr": 31,
      "author": {
        "id": 2651
      },
      "writtenOn": "2017-01-10T02:32:23Z",
      "side": 1,
      "message": "weird, logging within logger definition?",
      "revId": "96df70da90250b375b73aee4793238a15a5ba977",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5ac10518_af5f7140",
        "filename": "functest/utils/functest_logger.py",
        "patchSetId": 13
      },
      "lineNbr": 62,
      "author": {
        "id": 2651
      },
      "writtenOn": "2017-01-10T02:32:23Z",
      "side": 1,
      "message": "Sorry, I don\u0027t know how to describe it clearly, but it is kind of confused to mix method definition with actual execution, in line 40 and line 62",
      "revId": "96df70da90250b375b73aee4793238a15a5ba977",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}