{
  "comments": [
    {
      "key": {
        "uuid": "dad5f5cf_f0cdb987",
        "filename": "ci/run_tests.py",
        "patchSetId": 2
      },
      "lineNbr": 122,
      "author": {
        "id": 459
      },
      "writtenOn": "2016-10-13T15:00:09Z",
      "side": 1,
      "message": "Is the value of TestCasesBase.EX_OK 0?",
      "revId": "dd0bdff330875c523792aae6c40747ec6094589e",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "dad5f5cf_fd403237",
        "filename": "testcases/Controllers/ODL/OpenDaylightTesting.py",
        "patchSetId": 2
      },
      "lineNbr": 120,
      "author": {
        "id": 2651
      },
      "writtenOn": "2016-10-13T01:39:42Z",
      "side": 1,
      "message": "if self.res_dir not exist, will the following work success? I see it bases on this dir",
      "revId": "dd0bdff330875c523792aae6c40747ec6094589e",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "dad5f5cf_10c15d80",
        "filename": "testcases/Controllers/ODL/OpenDaylightTesting.py",
        "patchSetId": 2
      },
      "lineNbr": 120,
      "author": {
        "id": 3405
      },
      "writtenOn": "2016-10-13T13:11:48Z",
      "side": 1,
      "message": "That\u0027s why I create it if it doesn\u0027t exist.",
      "parentUuid": "dad5f5cf_fd403237",
      "revId": "dd0bdff330875c523792aae6c40747ec6094589e",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "dad5f5cf_10e4fd0b",
        "filename": "testcases/Controllers/ODL/OpenDaylightTesting.py",
        "patchSetId": 2
      },
      "lineNbr": 120,
      "author": {
        "id": 3405
      },
      "writtenOn": "2016-10-13T14:29:44Z",
      "side": 1,
      "message": "It\u0027s passed as makedirs raises OSError if directory already exists. I could check what happen if disk is full or if root can\u0027t create the directory.",
      "parentUuid": "dad5f5cf_10c15d80",
      "revId": "dd0bdff330875c523792aae6c40747ec6094589e",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "dad5f5cf_90a6adc0",
        "filename": "testcases/Controllers/ODL/OpenDaylightTesting.py",
        "patchSetId": 2
      },
      "lineNbr": 120,
      "author": {
        "id": 459
      },
      "writtenOn": "2016-10-13T15:00:09Z",
      "side": 1,
      "message": "It\u0027s ok like this. Python 3.4 has a similar function that mkdir -p  in bash, but here we need to use the try-except",
      "parentUuid": "dad5f5cf_10e4fd0b",
      "revId": "dd0bdff330875c523792aae6c40747ec6094589e",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "dad5f5cf_bd4aaa53",
        "filename": "testcases/Controllers/ODL/OpenDaylightTesting.py",
        "patchSetId": 2
      },
      "lineNbr": 145,
      "author": {
        "id": 2651
      },
      "writtenOn": "2016-10-13T01:39:42Z",
      "side": 1,
      "message": "for try in one method?",
      "revId": "dd0bdff330875c523792aae6c40747ec6094589e",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "dad5f5cf_10487d2c",
        "filename": "testcases/Controllers/ODL/OpenDaylightTesting.py",
        "patchSetId": 2
      },
      "lineNbr": 145,
      "author": {
        "id": 3405
      },
      "writtenOn": "2016-10-13T13:15:06Z",
      "side": 1,
      "message": "In this case it\u0027s not justified as the first instructions cannot raise exceptions... Maybe true when  get_keystone_client will raise an exception.",
      "parentUuid": "dad5f5cf_bd4aaa53",
      "revId": "dd0bdff330875c523792aae6c40747ec6094589e",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}